/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author lenovo
 */

import Data.*;

import javax.swing.JOptionPane;

public class FrmLogIn extends javax.swing.JFrame {

  Data data;
  private CListaUsuarios listaUsuarios;
  
 
    public FrmLogIn(Data data) {
        initComponents();
        this.data=data;
        this.setTitle("Ugallery");
        listaUsuarios=data.getListaUsuarios();
        
    
    
    
        //CListaUsuario listaUsuarios = new CListaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelBiblioteca = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnIngresarBiblioteca = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresoEditor = new javax.swing.JButton();
        btnIngresoConvertidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido a Ugallery");

        jPanelBiblioteca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Biblioteca");

        btnIngresarBiblioteca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresarBiblioteca.setText("Ingresar a Biblioteca");
        btnIngresarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarBibliotecaActionPerformed(evt);
            }
        });

        btnCrearUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBibliotecaLayout = new javax.swing.GroupLayout(jPanelBiblioteca);
        jPanelBiblioteca.setLayout(jPanelBibliotecaLayout);
        jPanelBibliotecaLayout.setHorizontalGroup(
            jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBibliotecaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnIngresarBiblioteca)
                .addGap(39, 39, 39)
                .addComponent(btnCrearUsuario)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBibliotecaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBibliotecaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBibliotecaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(142, 142, 142))))
        );
        jPanelBibliotecaLayout.setVerticalGroup(
            jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarBiblioteca)
                    .addComponent(btnCrearUsuario))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Menu");

        btnIngresoEditor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresoEditor.setText("Ingresar a Editor");
        btnIngresoEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoEditorActionPerformed(evt);
            }
        });

        btnIngresoConvertidor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresoConvertidor.setText("Ingresar a Convertidor");
        btnIngresoConvertidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoConvertidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnIngresoEditor))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnIngresoConvertidor)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresoEditor)
                .addGap(32, 32, 32)
                .addComponent(btnIngresoConvertidor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanelBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoConvertidorActionPerformed
        if(evt.getSource()== btnIngresoConvertidor){
            FrmLotesEditor lotes = new FrmLotesEditor(data);  
            lotes.setDefaultCloseOperation(FrmEditor.DISPOSE_ON_CLOSE);
            lotes.setLocationRelativeTo(null);
            lotes.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnIngresoConvertidorActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
       if(evt.getSource()==btnCrearUsuario){
           FrmCrearUsuario frmCrearUsuario = new FrmCrearUsuario(data);     
            frmCrearUsuario.setDefaultCloseOperation(FrmCrearUsuario.DISPOSE_ON_CLOSE);
            frmCrearUsuario.setLocationRelativeTo(null);
            frmCrearUsuario.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnIngresarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarBibliotecaActionPerformed
        String usuario = txtUsuario.getText().trim();
        
        if( usuario.isBlank()){
            JOptionPane.showMessageDialog(this, "Ingrese usuario!", "Error", JOptionPane.ERROR_MESSAGE);
            txtUsuario.setText("");
            return;
        }
        
        CNodoUsuario nodoUsuario = listaUsuarios.GetUsuario(usuario);
        
            if(nodoUsuario != null){
                //String usuarioEncontrado = nodoUsuario.GetNodoUsuario();
                FrmBiblioteca frmBiblioteca = new FrmBiblioteca(data, nodoUsuario.getNombreUsuario());     
                frmBiblioteca.setDefaultCloseOperation(FrmBiblioteca.DISPOSE_ON_CLOSE);
                frmBiblioteca.setLocationRelativeTo(null);
                frmBiblioteca.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
                txtUsuario.setText("");
            }
        
        
    }//GEN-LAST:event_btnIngresarBibliotecaActionPerformed

    private void btnIngresoEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoEditorActionPerformed
       if(evt.getSource()== btnIngresoEditor){
            FrmEditor editor = new FrmEditor(data);  
            editor.setDefaultCloseOperation(FrmEditor.DISPOSE_ON_CLOSE);
            editor.setLocationRelativeTo(null);
            editor.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnIngresoEditorActionPerformed

    
            public void CloseAutenticacion(){
            super.dispose();
        }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmLogIn().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnIngresarBiblioteca;
    private javax.swing.JButton btnIngresoConvertidor;
    private javax.swing.JButton btnIngresoEditor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelBiblioteca;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
